# This sample code illustrates the creation of a procfs entry 
#
# compilation:
#  make -C /usr/src/linux-headers-3.8.0-31-generic/ M=$PWD modules
# clean:
#  make -C /usr/src/linux-headers-3.8.0-31-generic/ M=$PWD clean
#
# Author: Vysakh P Pillai [vysakhpillai[at]gmail.com]
obj-m = procfs.o
