#This example is to create a blank kernel object . This is mostly to test your compilation environment.
#sample commands:
# compilation:
#  make -C /usr/src/linux-headers-3.8.0-31-generic/ M=$PWD modules
# clean:
#  make -C /usr/src/linux-headers-3.8.0-31-generic/ M=$PWD clean
#
#
# Author: Vysakh P Pillai [vysakhpillai[at]gmail.com]
obj-m := blank.o
