# This sample code illustrated differentiating different minor numbers from the driver code using 
#information stored in the file pointer inode object 
#
# compilation:
#  make -C /usr/src/linux-headers-3.8.0-31-generic/ M=$PWD modules
# clean:
#  make -C /usr/src/linux-headers-3.8.0-31-generic/ M=$PWD clean
# node creation:
#  mknod filep0 c 250 0 
#  mknod filep1 c 250 1
#  mknod filep2 c 250 2 #- to see invalid case
#
# Author: Vysakh P Pillai [vysakhpillai[at]gmail.com]
obj-m := filep.o
